name: Validate Cards

on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  validate-cards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Find changed card files
        id: changed-files
        uses: actions/github-script@v8
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const files = await github.rest.pulls.listFiles({ owner, repo, pull_number: number });
            const changedCardFiles = files.data
              .filter(file =>
                (file.status === 'added' || file.status === 'modified') &&
                file.filename.startsWith('cards/') &&
                file.filename.endsWith('.md')
              )
              .map(file => file.filename);
            core.setOutput('files', changedCardFiles.join(' '));
            core.setOutput('count', changedCardFiles.length);

      - name: Validate changed cards
        run: |
          if [ "${{ steps.changed-files.outputs.count }}" = "0" ]; then
            echo "No card files changed - validation passes"
            exit 0
          fi

          FILES="${{ steps.changed-files.outputs.files }}"
          OVERALL_SUCCESS=true

          for file in $FILES; do
            echo "Validating $file..."
            if ! npm run validate "$file"; then
              OVERALL_SUCCESS=false
            fi
          done

          if [ "$OVERALL_SUCCESS" = "false" ]; then
            echo "Some card validations failed"
            exit 1
          fi

          echo "All card files passed validation"